from MongoConstants import MONGO_LESS_THAN, MONGO_LESS_THAN_EQ, \
    MONGO_GREATER_THAN, MONGO_GREATER_THAN_EQ, MONGO_NOT_EQUAL

OPERATOR_MAPPING = {
    MONGO_LESS_THAN: '<',
    MONGO_LESS_THAN_EQ: '<=',
    MONGO_GREATER_THAN: '>',
    MONGO_GREATER_THAN_EQ: '>=',
    MONGO_NOT_EQUAL: '!='
}
SQL_AND = "AND"
SQL_OR = "OR"
SQL_IS = "IS"
SQL_IS_NOT = "IS NOT"
SQL_EQ = "="
SQL_IN = "IN"
SQL_NULL = 'NULL'
SQL_ALL = '*'
